#!/bin/bash

TOUCHSCREEN_INPUT="Wacom HID 48EB Finger touch"

function get_id {
    echo $(xinput --list | grep "$1" | grep -Eo "id=([0-9]+)" | cut -d= -f2)
}

function map_screen {
    xinput --map-to-output "${TOUCHSCREEN_INPUT}" eDP1
}

function touchscreen {
    local verb=enable
    if [[ $1 == "off" ]]; then
        verb=disable
    elif [[ $1 == "on" ]]; then
        verb=enable
    fi
    xinput --$verb "$screen_id"
}

function rotate {
    local mtx="1 0 0 0 1 0 0 0 1"
    if [[ $1 == "normal" ]]; then
        mtx="1 0 0 0 1 0 0 0 1"
    elif [[ $1 == "inverted" ]]; then
        mtx="-1 0 1 0 -1 1 0 0 1"
    elif [[ $1 == "right" ]]; then
        mtx="0 1 0 -1 0 1 0 0 1"
    elif [[ $1 == "left" ]]; then
        mtx="0 -1 1 1 0 0 0 0 1"
    fi
    xrandr -o $1
    xinput set-prop "${TOUCHSCREEN_INPUT}" "Coordinate Transformation Matrix" $mtx
}

if [[ $1 = "rotate" ]]; then
    rotate $2
elif [[ $1 = "screen" ]]; then
    touchscreen $2
fi

xrandr --output eDP1 --scale 1.5x1.5
map_screen
