#!/bin/sh

polybar-msg cmd quit

PRIMARY=$(xrandr | grep primary | cut -f1 -d' ')
SECONDARIES=$(xrandr --listactivemonitors | tail -n +2 | grep -v '*' | cut -d' ' -f '6')

echo "Primary: $PRIMARY"
echo "Secondaries: $SECONDARIES"

MONITOR=$PRIMARY polybar primary -r &

for M in $SECONDARIES; do
    MONITOR=$M polybar secondary -r &
done
