#!/bin/bash

arg=$1
if [[ $arg = '-f' ]]; then
    timestamp=$(date +%Y-%m-%d:%H-%M-%S)
    name=$2
    if [ -z "$name" ]; then
        maim --nodrag -s > ~/$timestamp.png
    else
        maim --nodrag -s > ~/$timestamp\_$name.png
    fi
else
    # By default: store into clipboard
    maim --nodrag -s -u | xclip -selection clipboard -t image/png -i
fi
