#!/bin/bash

xmodmap ~/.Xmodmap
wallpaper
i3-msg '[class=".*"]' move workspace to output primary
i3-msg '[workspace="0"]' move workspace to output eDP1
i3-msg '[class="Google-chrome"]' focus
i3-msg '[class="Firefox"]' focus
